[build]
  # Build command
  command = "cd client && npm install && npm run build"
  
  # Directory to publish
  publish = "client/build"
  
  # Base directory (optional)
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
